FinalExamPractice/Controllers/AuctionController.cs
using FinalExamPractice.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalExamPractice.Controllers
{
    public class AuctionController : Controller
    {
        private IItemManager _itemManager;

        public AuctionController(IItemManager itemManager)
        {
            _itemManager = itemManager;
        }
        // GET: Auction
        public ActionResult ItemsView()
        {
            return View(_itemManager.ItemList);
        }

        public ActionResult PlaceBid(string Bid, int itemId)
        {
            decimal bidParsed = decimal.Parse(Bid);
            User user = Session["User"] as User;
            _itemManager.UpdateItemBid(itemId, user.Username, bidParsed);
            return RedirectToAction("ItemsView");

        }
    }
}

FinalExamPractice/Controllers/UserAccountController.cs
using FinalExamPractice.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalExamPractice.Controllers
{
    public class UserAccountController : Controller
    {
        private IUserManager _userManager;

        public UserAccountController(IUserManager userManager)
        {
            // make a variable equal the IUserManager binding
            _userManager = userManager;
        }
        // GET: UserAccount
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult CreateAccount()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateAccount(User user)
        {
            _userManager.AddUser(user);
            return RedirectToAction("Index");
        }

       
       
        public ActionResult Login(string username,string password)
        {
            User verfiyingUser = _userManager.RetrieveUsers.FirstOrDefault(x=>x.Username == username && x.Password == password);
            if(verfiyingUser != null)
            {
                Session["User"] = verfiyingUser;
                return RedirectToAction("ItemsView", "Auction");
            }else
            {
                return View("Index");
            }
        }
    }
}

FinalExamPractice/Views/Auction/ItemsView.cshtml
@using FinalExamPractice.Domain.Entities
@model IEnumerable<Item>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ItemsView</title>
</head>
<body>
    <div>
        @if (Session["User"] != null)
        {
            User user = Session["User"] as User;
            <h1>Welcome @user.Username </h1>
           <table>
               <thead><tr><th>Item Name</th><th>Current Highest Bid</th><th>Bid Holder</th><th>Place Bid</th>
                   </tr></thead>
               <tbody>
                   @foreach(Item item in Model)
                   {
                       <tr>
                          <td>@item.Name</td>
                           <td>@item.CurrentBidPrice</td>
                           <td>
                               @if(item.HolderName != null)
                               {
                                   @item.HolderName;
                               }
                               else
                               {
                                   @: No one has Bid on this Item yet
                               }
                           </td>
                           @using (Html.BeginForm("PlaceBid", "Auction", "Post"))
                           {
                               @Html.Hidden("itemId",item.ItemId)
                              
                            <td>@Html.TextBox("Bid")</td>
                                <td><input type="submit" value="Please Bid" /></td>
                           }
                          
                       </tr>
                   }
               </tbody>
           </table>
            
        }
        else
        {
            <p>Not Autheicated</p>
        }
    </div>
   
</body>
</html>

FinalExamPractice/Views/UserAccount/CreateAccount.cshtml
@using FinalExamPractice.Domain.Entities
@model User

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateAccount</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm("CreateAccount","UserAccount","Post"))
        {
            <label>Please Type Your Desired Username</label>@Html.TextBoxFor(x => x.Username);
            <label>Please Type Your Desired Password</label>@Html.PasswordFor(x => x.Password);
            <input type="submit" value="Create User" />
        }
       
    </div>
</body>
</html>

FinalExamPractice/Views/UserAccount/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Login", "UserAccount", "Post"))
        {
            <label>Username</label>@Html.TextBox("username")<br />
            <label>Password</label>@Html.Password("password")<br />
            <input type="submit" value="Login" />
        }

    </div>
    <div> 
        @Html.ActionLink("Create Account", "CreateAccount")
       
    </div>
</body>
</html>